// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeriv4sc4Uo6-4aVL3s3HP9DIlzSbQ9FM',
    appId: '1:1064144916466:android:bdab34a8a7207af036256b',
    messagingSenderId: '1064144916466',
    projectId: 'watchhub-flutter',
    authDomain: 'watchhub-flutter.firebaseapp.com ',
    databaseURL: 'https://watchhub-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'watchhub-flutter.firebasestorage.app',
    // measurementId: 'G-T7G5S4VHVB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeriv4sc4Uo6-4aVL3s3HP9DIlzSbQ9FM',
    appId: '1:1064144916466:android:bdab34a8a7207af036256b',
    messagingSenderId: '1064144916466',
    projectId: 'watchhub-flutter',
    databaseURL: 'https://watchhub-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'watchhub-flutter.firebasestorage.app',
  );
}
